name: CI Pipeline

on:
  push:
    branches-ignore:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [[ ! "$BRANCH_NAME" =~ ^feature/ ]]; then
            echo "Error: branch name must have prefix 'feature/'"
            exit 1
          fi
  lint:
    runs-on: ubuntu-latest
    needs: check-branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dependency install
        run: npm install

      - name: Lint the code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dependency install
        run: npm install

      - name: Test the code
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dependency install
        run: npm install

      - name: Build the project
        run: npm run build
